### ISSUE TITLE
Feature request: Bayesian optimization?

### ISSUE THREAD

**Issue by Lupus** [mmottl/gpr#5]
It seems that GPR library implements the core primitive used in Bayesian optimization, does it make sense to provide a high-level module for Bayesian optimization itself? With user-friendly interface like `Siman` from `ocaml-gsl`.

**Comment by mmottl** [comment]
It would certainly be nice to see Bayesian optimization, but it's probably not worth doing so for GPR in its current state.  GPR should be rewritten with algorithmic differentiation.  Not only could you train models considerably faster then, Bayesian optimization would be quite trivial to add.  I'm unfortunately too busy with other things right now to work on that, but feel free to submit any suggestions.  They could probably still be incorporated in an improved GPR library.
